Make public device on request and move some things to common
promotedai/schema pull request #16
Opened 2021-08-06 21:10 UTC by scottmcmaster

2021-08-06 21:27 UTC, jinyius requested changes

2021-08-06 21:27 UTC, jinyius commented on proto/delivery/delivery.proto
> +  reserved 15; // Deprecated
how'd this // Deprecated come in?  we shouldn't have to explain reserved fields.

2021-08-06 21:27 UTC, jinyius commented on proto/event/event.proto
>    // Optional.
hide this when reserved

2021-08-06 21:27 UTC, jinyius commented on proto/event/event.proto
>    // Optional.
same

2021-08-06 22:55 UTC, danbosnichill approved these changes

2021-08-07 01:56 UTC, jinyius approved these changes

2021-08-09 15:46 UTC, merged